baseURL = 'https://yongfrank.github.io/'
languageCode = 'en-us'
title = 'Blog by Frank'
theme = 'contrast-hugo'
googleAnalytics = 'G-XZQ6YTCMN7'

[params]
  minimal = false
  excerpts = false
  description = "my blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2